// Mirrors the GET /movies/ payload field for field, including already_seen and
// personal_rating, which this SPA never shows — a trimmed fixture hides surprises.
// Titles are deliberately uneven in length: a card grid has to survive both
// "Parasite" and a title that wraps to three lines.
export const MOVIES = [
  {
    tmdb_id: 550,
    title: 'Fight Club',
    release_date: '1999-10-15',
    poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    imdb_id: 'tt0137523',
    imdb_rating: 8.8,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    // No poster: TMDB leaves poster_path null for plenty of titles.
    tmdb_id: 680,
    title: 'Pulp Fiction',
    release_date: '1994-09-10',
    poster_path: null,
    imdb_id: 'tt0110912',
    imdb_rating: 8.9,
    already_seen: false,
    personal_rating: 0,
    is_favorite: true,
  },
  {
    // Absent from OMDB: both IMDb fields come back null.
    tmdb_id: 13,
    title: 'Forrest Gump',
    release_date: '1994-06-23',
    poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    imdb_id: null,
    imdb_rating: null,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 155,
    title: 'The Dark Knight',
    release_date: '2008-07-16',
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    imdb_id: 'tt0468569',
    imdb_rating: 9,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 27205,
    title: 'Inception',
    release_date: '2010-07-15',
    poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    imdb_id: 'tt1375666',
    imdb_rating: 8.8,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 157336,
    title: 'Interstellar',
    release_date: '2014-11-05',
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    imdb_id: 'tt0816692',
    imdb_rating: 8.7,
    already_seen: false,
    personal_rating: 0,
    is_favorite: true,
  },
  {
    // Watched and rated: fields the SPA ignores but the API always sends.
    tmdb_id: 603,
    title: 'The Matrix',
    release_date: '1999-03-30',
    poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    imdb_id: 'tt0133093',
    imdb_rating: 8.7,
    already_seen: true,
    personal_rating: 9,
    is_favorite: false,
  },
  {
    tmdb_id: 278,
    title: 'The Shawshank Redemption',
    release_date: '1994-09-23',
    poster_path: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    imdb_id: 'tt0111161',
    imdb_rating: 9.3,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 238,
    title: 'The Godfather',
    release_date: '1972-03-14',
    poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    imdb_id: 'tt0068646',
    imdb_rating: 9.2,
    already_seen: true,
    personal_rating: 10,
    is_favorite: false,
  },
  {
    tmdb_id: 496243,
    title: 'Parasite',
    release_date: '2019-05-30',
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    imdb_id: 'tt6751668',
    imdb_rating: 8.5,
    already_seen: false,
    personal_rating: 0,
    is_favorite: true,
  },
  {
    tmdb_id: 129,
    title: 'Spirited Away',
    release_date: '2001-07-20',
    poster_path: '/39wmItUWsg3sZmVd7cjmL97tqeB.jpg',
    imdb_id: 'tt0245429',
    imdb_rating: 8.6,
    already_seen: false,
    personal_rating: 0,
    is_favorite: true,
  },
  {
    tmdb_id: 769,
    title: 'GoodFellas',
    release_date: '1990-09-12',
    poster_path: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    imdb_id: 'tt0099685',
    imdb_rating: 8.7,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 424,
    title: "Schindler's List",
    release_date: '1993-12-15',
    poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    imdb_id: 'tt0108052',
    imdb_rating: 9,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    // The longest title in the fixture: it wraps to three lines in a phone column.
    tmdb_id: 122,
    title: 'The Lord of the Rings: The Return of the King',
    release_date: '2003-12-17',
    poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    imdb_id: 'tt0167260',
    imdb_rating: 9,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 1891,
    title: 'The Empire Strikes Back',
    release_date: '1980-05-20',
    poster_path: '/7BuH8itoSrLExs2YZSsM01Qk2no.jpg',
    imdb_id: 'tt0080684',
    imdb_rating: 8.7,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 389,
    title: '12 Angry Men',
    release_date: '1957-04-10',
    poster_path: '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
    imdb_id: 'tt0050083',
    imdb_rating: 9,
    already_seen: false,
    personal_rating: 0,
    is_favorite: true,
  },
  {
    tmdb_id: 372058,
    title: 'Your Name.',
    release_date: '2016-08-26',
    poster_path: '/q719jXXEzOoYaps6babgKnONONX.jpg',
    imdb_id: 'tt5311514',
    imdb_rating: 8.4,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 274,
    title: 'The Silence of the Lambs',
    release_date: '1991-02-14',
    poster_path: '/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
    imdb_id: 'tt0102926',
    imdb_rating: 8.6,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 637,
    title: 'Life Is Beautiful',
    release_date: '1997-12-20',
    poster_path: '/74hLDKjD5aGYOotO6esUVaeISa2.jpg',
    imdb_id: 'tt0118799',
    imdb_rating: 8.6,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
  {
    tmdb_id: 1124,
    title: 'The Prestige',
    release_date: '2006-10-19',
    poster_path: '/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg',
    imdb_id: 'tt0482571',
    imdb_rating: 8.5,
    already_seen: false,
    personal_rating: 0,
    is_favorite: false,
  },
]
