"""Minor changes in naming

Revision ID: 17feed681782
Revises: 104ed420c1f6
Create Date: 2025-02-27 10:25:45.015113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17feed681782'
down_revision: Union[str, None] = '104ed420c1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies to be watched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.DATE(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('imdb_rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.drop_table('movies to be seen')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies to be seen',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('imdb_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('imdb_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='movies to be seen_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='movies to be seen_pkey'),
    sa.UniqueConstraint('imdb_id', name='movies to be seen_imdb_id_key'),
    sa.UniqueConstraint('tmdb_id', name='movies to be seen_tmdb_id_key')
    )
    op.drop_table('movies to be watched')
    # ### end Alembic commands ###
