"""New table watched movies

Revision ID: 94ea0e333dff
Revises: a28ef93fba14
Create Date: 2025-02-24 16:16:34.052083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ea0e333dff'
down_revision: Union[str, None] = 'a28ef93fba14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.DATE(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('imdb_rating', sa.Integer(), nullable=False),
    sa.Column('personal_rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched movies')
    # ### end Alembic commands ###
