"""Changed watched movies tables

Revision ID: ada860ce836a
Revises: 58b8d6819429
Create Date: 2025-02-24 17:03:15.612014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada860ce836a'
down_revision: Union[str, None] = '58b8d6819429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'watched movies', ['tmdb_id'])
    op.create_unique_constraint(None, 'watched movies', ['imdb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watched movies', type_='unique')
    op.drop_constraint(None, 'watched movies', type_='unique')
    # ### end Alembic commands ###
