"""added unique constraint

Revision ID: 016d63fed629
Revises: 17feed681782
Create Date: 2026-07-07 09:59:29.098469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016d63fed629'
down_revision: Union[str, None] = '17feed681782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movies to be watched_imdb_id_key'), 'movies to be watched', type_='unique')
    op.drop_constraint(op.f('movies to be watched_tmdb_id_key'), 'movies to be watched', type_='unique')
    op.create_unique_constraint('uq_user_movie', 'movies to be watched', ['user_id', 'tmdb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_movie', 'movies to be watched', type_='unique')
    op.create_unique_constraint(op.f('movies to be watched_tmdb_id_key'), 'movies to be watched', ['tmdb_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('movies to be watched_imdb_id_key'), 'movies to be watched', ['imdb_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
