"""Constraints again

Revision ID: dd1da675dc2e
Revises: 016d63fed629
Create Date: 2026-07-08 16:04:27.357045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd1da675dc2e"
down_revision: Union[str, None] = "016d63fed629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("watched movies_imdb_id_key"), "watched movies", type_="unique"
    )
    op.drop_constraint(
        op.f("watched movies_tmdb_id_key"), "watched movies", type_="unique"
    )
    op.create_unique_constraint(
        "uq_watched_movie", "watched movies", ["user_id", "tmdb_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_movie", "watched movies", type_="unique")
    op.create_unique_constraint(
        op.f("watched movies_tmdb_id_key"),
        "watched movies",
        ["tmdb_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("watched movies_imdb_id_key"),
        "watched movies",
        ["imdb_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
